name: FundsDB ZKEngine Proof Check

on:
  pull_request:
    branches: [ main ]

jobs:
  proof-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install zkengine

      - name: Validate Queries with FundsDB ZKEngine
        run: node scripts/validateProof.js
